error: cannot use 'throw' with exceptions disabled
